package controladorqytetet;


public enum OpcionMenu {
    INICIARJUEGO,
    JUGAR,
    APLICARSORPRESA,
    INTENTARSALIRCARCELPAGANDOLIBERTAD,
    INTENTARSALIRCARCELTIRANDODADO,
    COMPRARTITULOPROPIEDAD,
    CANCELARHIPOTECA,
    EDIFICARCASA,
    EDIFICARHOTEL,
    VENDERPROPIEDAD,
    PASARTURNO,
    OBTENERRANKING,
    TERMINARJUEGO,
    MOSTRARJUGADORACTUAL,
    MOSTRARJUGADRES,
    MOSTRARTABLERO,
    HIPOTECARPROPIEDAD
}
